Created Works and about myself section
fatmahussein/_Portfolio pull request #4
Opened 2023-05-30 12:09 UTC by fatmahussein

- Add portfolio works section
- Add about myself section

2023-05-30 12:59 UTC, Olamarx requested changes
Hi @fatmahussein, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the readme of hello world, kindly k=remember that this is a portfolio project, kindly make your readme data reflect this.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-30 17:33 UTC, divinecharlotte requested changes
Hi @fatmahussein          , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Linters set up correctly 👍 
- Descriptive Pr 👍 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 17:33 UTC, divinecharlotte commented on index.html
> +          <button type="button" class="see-project">See Project</button>
- [ ] kindly consider making sure that this button follow the button styling: Active, Hover and Pressed as given in the design to improve user experience

2023-05-30 17:33 UTC, divinecharlotte commented on index.html
> +          </ul>
- [ ] kindly consider giving this section the same fonts as given in the design to make your project an exact duplicate of the given one check the images below to see the difference 
- your design 👇 
<img width="327" alt="Screen Shot 2023-05-30 at 19 09 15" src="https://github.com/fatmahussein/_Portfolio/assets/60146030/45c4b8b3-f944-45af-ace4-eb5a2a8187df">



- given design 👇 
<img width="371" alt="Screen Shot 2023-05-30 at 19 09 49" src="https://github.com/fatmahussein/_Portfolio/assets/60146030/747b1619-50db-4869-83c0-ca6f09ee3b8b">

2023-05-30 17:33 UTC, divinecharlotte commented on index.html
> +  <a class="connect" href="#">LET’S CONNECT</a>
- [ ] kindly consider making sure that this link is enclosed in an hx tag to meet the below requirement
> If there are other titles (e.g., "Let's connect") use a header tag `hx`

2023-05-30 17:33 UTC, divinecharlotte commented on index.html
> +  <button type="button" class="resume">Get my resume</button>
- [ ]  kindly consider making sure that this button follow the button styling: Active, Hover and Pressed as given in the design to improve user experience

2023-05-30 17:33 UTC, divinecharlotte commented on index.html
> +      <h5 class="skills">Skills<i class="fa fa-angle-right" ></i></h5>
- [ ] Kindly consider adding The technology categories ("Languages", "Frameworks" and "Skills") in a `ul`, each of them in a `li` because we use the <ul> tag together with the <li> tag to create unordered lists and they are

2023-05-30 17:33 UTC, divinecharlotte commented on styles.css
> +  border-top-right-radius: 15%;
- [ ] kindly consider giving this radius a value in pixels to make it look exactly like the one given in the design check the images below to see the difference 
- your design 👇 
<img width="376" alt="Screen Shot 2023-05-30 at 19 29 53" src="https://github.com/fatmahussein/_Portfolio/assets/60146030/e08fa0bf-2410-47ac-b58e-c62a58d6432d">


- Figma design 👇 
<img width="370" alt="Screen Shot 2023-05-30 at 19 30 35" src="https://github.com/fatmahussein/_Portfolio/assets/60146030/bbbd1d03-2c99-43da-991a-f6f28cea91ed">

2023-05-31 19:59 UTC, Johnadibe requested changes
# Status: Required Changes ♻️
### Hi @fatmahussein🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- No linter errors ✔️
- Your project is documented professionally✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 19:59 UTC, Johnadibe commented on index.html
> +  <a class="connect" href="#">LET’S CONNECT</a>
> - [ ] Good job so far👍, The previous reviewer recommends including an hx tag (h4, h5, ...) around this link to meet the specified requirement, which you haven't implemented. Utilizing heading tags offers improving search engine optimization (SEO) and enhances accessibility.😊

2023-05-31 19:59 UTC, Johnadibe commented on styles.css
> +
> [OPTIONAL] I suggest you increase the width of the card container to 90% so that it can match the given Figma design👍

Figma design:

![abt1](https://github.com/fatmahussein/_Portfolio/assets/40009354/0a591985-3f88-4a17-b9a7-1854b8b9af1e)

Your design:

![abt](https://github.com/fatmahussein/_Portfolio/assets/40009354/793f8bda-0c71-4eb8-a315-2bfeb66dc440)

2023-06-01 06:34 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi @fatmahussein 👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ Descriptive PR👍
✔ Made the suggested changes👍
✔ Professional README👍
✔ Awesome design👍
### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 07:11 UTC, merged