Created desktop version
fatmahussein/_Portfolio pull request #6
Opened 2023-06-07 11:11 UTC by fatmahussein

-  Added  CSS media query for desktop version

2023-06-07 13:08 UTC, skyv26 requested changes
## Hi @fatmahussein, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTY5MTMxNDUzNWFmNjU5MmFjOWZjY2IyMDIyY2RhNWFlYmU4NjdlNCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Xfb7kQ0VhUIrpiuGx1/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 
- Linters are green ✅
- Correct `.github/workflows` for linters ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 13:08 UTC, skyv26 commented on styles.css
> +  }
- [ ] Please adhere to the Figma design it seems like while implementing the desktop version your mobile design is messed up. Kindly take care of mobile design while implementing the responsiveness for a wider screen.

###  Design Comparison

<table>
<tr>
<th>Your Design</th>
<th>Figma Design</th>
</tr>

<tr>
<td>

![image](https://github.com/fatmahussein/_Portfolio/assets/66476329/31e680a1-d2fa-4ad5-85e0-6f2a322a3759)



</td>

<td>

![Screenshot from 2023-06-07 18-32-02](https://github.com/fatmahussein/_Portfolio/assets/66476329/5607b6f5-d621-43f9-8088-e3aa8e9394c4)


</td>
</tr>
</table>

2023-06-07 13:08 UTC, skyv26 commented on styles.css
> +@media screen and (min-width: 375px) {
- [ ] Please remove this line because the CSS style that you added is automatically picked up by your HTML and when it will encounter the media query let's say for screen size >=768px it will then change its style according to what you have added because mobile-first means writing the styles for mobile without explicitly tell the breakpoint like what you did.

2023-06-08 09:01 UTC, Olamarx approved these changes
Hi @fatmahussein,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>
## Highlights
- Linters passed ✔️
- Required changes fixed ✔️
- Commit messages meaningful ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 09:09 UTC, merged